#ifndef VOCAB_H
#define VOCAB_H

#include <avr/pgmspace.h>
#include <stdint.h>

/*
 * Token/char mapping — 41 tokens.
 * Generated by export.py from meta.json
 */

static const char vocab_chars[41] PROGMEM = {
    '\n',  /*  0 */
    ' ',   /*  1 */
    '-',   /*  2 */
    '.',   /*  3 */
    '/',   /*  4 */
    '0',   /*  5 */
    '1',   /*  6 */
    '2',   /*  7 */
    '3',   /*  8 */
    '4',   /*  9 */
    '5',   /* 10 */
    '6',   /* 11 */
    '7',   /* 12 */
    '8',   /* 13 */
    '9',   /* 14 */
    'a',   /* 15 */
    'b',   /* 16 */
    'c',   /* 17 */
    'd',   /* 18 */
    'e',   /* 19 */
    'f',   /* 20 */
    'g',   /* 21 */
    'h',   /* 22 */
    'i',   /* 23 */
    'j',   /* 24 */
    'k',   /* 25 */
    'l',   /* 26 */
    'm',   /* 27 */
    'n',   /* 28 */
    'o',   /* 29 */
    'p',   /* 30 */
    'q',   /* 31 */
    'r',   /* 32 */
    's',   /* 33 */
    't',   /* 34 */
    'u',   /* 35 */
    'v',   /* 36 */
    'w',   /* 37 */
    'x',   /* 38 */
    'y',   /* 39 */
    'z'   /* 40 */
};

static inline uint8_t vocab_encode(char ch)
{
    for (uint8_t i = 0; i < 41; i++) {
        if (pgm_read_byte(&vocab_chars[i]) == (uint8_t)ch)
            return i;
    }
    return 0;
}

static inline char vocab_decode(uint8_t idx)
{
    if (idx >= 41) return '?';
    return (char)pgm_read_byte(&vocab_chars[idx]);
}

#endif /* VOCAB_H */
